const container2 = document.getElementsByClassName("container2")[0];
const namebox = document.getElementById("namebox");
const phonebox = document.getElementById("phonebox");
const opsubmit = document.getElementById("opsubmit");
const opclear = document.getElementById("opsubmit");
const opshow = document.getElementById("opshow");
const sign = document.getElementById("sign");
const textboxs = document.getElementById("textboxs");
const name1 = document.getElementsByClassName("name1")[0];
const phone1 = document.getElementsByClassName("phone1")[0];
const name2 = document.getElementsByClassName("name2")[0];
const phone2 = document.getElementsByClassName("phone2")[0];
const name3 = document.getElementsByClassName("name3")[0];
const phone3 = document.getElementsByClassName("phone3")[0];
const name4 = document.getElementsByClassName("name4")[0];
const phone4 = document.getElementsByClassName("phone4")[0];
const name5 = document.getElementsByClassName("name5")[0];
const phone5 = document.getElementsByClassName("phone5")[0];
const name6 = document.getElementsByClassName("name6")[0];
const phone6 = document.getElementsByClassName("phone6")[0];
const name7 = document.getElementsByClassName("name7")[0];
const phone7 = document.getElementsByClassName("phone7")[0];
const name8 = document.getElementsByClassName("name8")[0];
const phone8 = document.getElementsByClassName("phone8")[0];
const name9 = document.getElementsByClassName("name9")[0];
const phone9 = document.getElementsByClassName("phone9")[0];
const name10 = document.getElementsByClassName("name10")[0];
const phone10 = document.getElementsByClassName("phone10")[0];
const name11 = document.getElementsByClassName("name11")[0];
const phone11 = document.getElementsByClassName("phone11")[0];
const name12 = document.getElementsByClassName("name12")[0];
const phone12 = document.getElementsByClassName("phone12")[0];
const name13 = document.getElementsByClassName("name13")[0];
const phone13 = document.getElementsByClassName("phone13")[0];
const name14 = document.getElementsByClassName("name14")[0];
const phone14 = document.getElementsByClassName("phone14")[0];
const name15 = document.getElementsByClassName("name15")[0];
const phone15 = document.getElementsByClassName("phone15")[0];
const name16 = document.getElementsByClassName("name16")[0];
const phone16 = document.getElementsByClassName("phone16")[0];
const name17 = document.getElementsByClassName("name17")[0];
const phone17 = document.getElementsByClassName("phone17")[0];
const name18 = document.getElementsByClassName("name18")[0];
const phone18 = document.getElementsByClassName("phone18")[0];
const name19 = document.getElementsByClassName("name19")[0];
const phone19 = document.getElementsByClassName("phone19")[0];
const name20 = document.getElementsByClassName("name20")[0];
const phone20 = document.getElementsByClassName("phone20")[0];
const name21 = document.getElementsByClassName("name21")[0];
const phone21 = document.getElementsByClassName("phone21")[0];
const name22 = document.getElementsByClassName("name22")[0];
const phone22 = document.getElementsByClassName("phone22")[0];
const name23 = document.getElementsByClassName("name23")[0];
const phone23 = document.getElementsByClassName("phone23")[0];
const name24 = document.getElementsByClassName("name24")[0];
const phone24 = document.getElementsByClassName("phone24")[0];
const name25 = document.getElementsByClassName("name25")[0];
const phone25 = document.getElementsByClassName("phone25")[0];
const name26 = document.getElementsByClassName("name26")[0];
const phone26 = document.getElementsByClassName("phone26")[0];
const name27 = document.getElementsByClassName("name27")[0];
const phone27 = document.getElementsByClassName("phone27")[0];
const name28 = document.getElementsByClassName("name28")[0];
const phone28 = document.getElementsByClassName("phone28")[0];
const name29 = document.getElementsByClassName("name29")[0];
const phone29 = document.getElementsByClassName("phone29")[0];
const name30 = document.getElementsByClassName("name30")[0];
const phone30 = document.getElementsByClassName("phone30")[0];
const name31 = document.getElementsByClassName("name31")[0];
const phone31 = document.getElementsByClassName("phone31")[0];
const name32 = document.getElementsByClassName("name32")[0];
const phone32 = document.getElementsByClassName("phone32")[0];
const name33 = document.getElementsByClassName("name33")[0];
const phone33 = document.getElementsByClassName("phone33")[0];
const name34 = document.getElementsByClassName("name34")[0];
const phone34 = document.getElementsByClassName("phone34")[0];
const name35 = document.getElementsByClassName("name35")[0];
const phone35 = document.getElementsByClassName("phone35")[0];
const name36 = document.getElementsByClassName("name36")[0];
const phone36 = document.getElementsByClassName("phone36")[0];
const name37 = document.getElementsByClassName("name37")[0];
const phone37 = document.getElementsByClassName("phone37")[0];
const name38 = document.getElementsByClassName("name38")[0];
const phone38 = document.getElementsByClassName("phone38")[0];
const name39 = document.getElementsByClassName("name39")[0];
const phone39 = document.getElementsByClassName("phone39")[0];
const name40 = document.getElementsByClassName("name40")[0];
const phone40 = document.getElementsByClassName("phone40")[0];
const name41 = document.getElementsByClassName("name41")[0];
const phone41 = document.getElementsByClassName("phone41")[0];
const name42 = document.getElementsByClassName("name42")[0];
const phone42 = document.getElementsByClassName("phone42")[0];
const name43 = document.getElementsByClassName("name43")[0];
const phone43 = document.getElementsByClassName("phone43")[0];
const name44 = document.getElementsByClassName("name44")[0];
const phone44 = document.getElementsByClassName("phone44")[0];
const name45 = document.getElementsByClassName("name45")[0];
const phone45 = document.getElementsByClassName("phone45")[0];
const name46 = document.getElementsByClassName("name46")[0];
const phone46 = document.getElementsByClassName("phone46")[0];
const name47 = document.getElementsByClassName("name47")[0];
const phone47 = document.getElementsByClassName("phone47")[0];
const name48 = document.getElementsByClassName("name48")[0];
const phone48 = document.getElementsByClassName("phone48")[0];
const name49 = document.getElementsByClassName("name49")[0];
const phone49 = document.getElementsByClassName("phone49")[0];
const name50 = document.getElementsByClassName("name50")[0];
const phone50 = document.getElementsByClassName("phone50")[0];
const name51 = document.getElementsByClassName("name51")[0];
const phone51 = document.getElementsByClassName("phone51")[0];
const name52 = document.getElementsByClassName("name52")[0];
const phone52 = document.getElementsByClassName("phone52")[0];
const name53 = document.getElementsByClassName("name53")[0];
const phone53 = document.getElementsByClassName("phone53")[0];
const name54 = document.getElementsByClassName("name54")[0];
const phone54 = document.getElementsByClassName("phone54")[0];
const name55 = document.getElementsByClassName("name55")[0];
const phone55 = document.getElementsByClassName("phone55")[0];
const name56 = document.getElementsByClassName("name56")[0];
const phone56 = document.getElementsByClassName("phone56")[0];
const name57 = document.getElementsByClassName("name57")[0];
const phone57 = document.getElementsByClassName("phone57")[0];
const name58 = document.getElementsByClassName("name58")[0];
const phone58 = document.getElementsByClassName("phone58")[0];
const name59 = document.getElementsByClassName("name59")[0];
const phone59 = document.getElementsByClassName("phone59")[0];
const name60 = document.getElementsByClassName("name60")[0];
const phone60 = document.getElementsByClassName("phone60")[0];
const name61 = document.getElementsByClassName("name61")[0];
const phone61 = document.getElementsByClassName("phone61")[0];
const name62 = document.getElementsByClassName("name62")[0];
const phone62 = document.getElementsByClassName("phone62")[0];
const name63 = document.getElementsByClassName("name63")[0];
const phone63 = document.getElementsByClassName("phone63")[0];
const name64 = document.getElementsByClassName("name64")[0];
const phone64 = document.getElementsByClassName("phone64")[0];
const name65 = document.getElementsByClassName("name65")[0];
const phone65 = document.getElementsByClassName("phone65")[0];
const name66 = document.getElementsByClassName("name66")[0];
const phone66 = document.getElementsByClassName("phone66")[0];
const name67 = document.getElementsByClassName("name67")[0];
const phone67 = document.getElementsByClassName("phone67")[0];
const name68 = document.getElementsByClassName("name68")[0];
const phone68 = document.getElementsByClassName("phone68")[0];
const name69 = document.getElementsByClassName("name69")[0];
const phone69 = document.getElementsByClassName("phone69")[0];
const name70 = document.getElementsByClassName("name70")[0];
const phone70 = document.getElementsByClassName("phone70")[0];

const clickSubmit = () =>{
	if(namebox.value === "" || phonebox.value === ""){
		sign.style.opacity = "1";
	sign.innerHTML = "❌ Information is required";
	setTimeout(()=>{
		sign.style.opacity = "0";
	},1000);
	}
	else{
	if(typeof(Storage) !== undefined){
		if(localStorage.clickcount){
			localStorage.clickcount = Number(localStorage.clickcount)+1;
		}
		else{
			localStorage.clickcount = 1;
		}
			sign.style.opacity = "1";
			if(localStorage.clickcount == 1){
				sign.innerHTML = `✅ ${localStorage.clickcount}st Contact saved!`;
			}
			else if(localStorage.clickcount == 2){
				sign.innerHTML = `✅ ${localStorage.clickcount}nd Contact saved!`;
			}
			else if(localStorage.clickcount == 3){
				sign.innerHTML = `✅ ${localStorage.clickcount}rd Contact saved!`;
			}
			else{
	sign.innerHTML = `✅ ${localStorage.clickcount}th Contact saved!`;
		}
	setTimeout(()=>{
		sign.style.opacity = "0";
	},1000);
		localStorage.setItem(`name${localStorage.clickcount}`,`${localStorage.clickcount}.<br> Name : ${namebox.value}<br>`);
		localStorage.setItem(`phone${localStorage.clickcount}`,` Phone : ${phonebox.value}<hr class="hrt">`);

	 name1.innerHTML = localStorage.getItem("name1");
	 phone1.innerHTML = localStorage.getItem("phone1");
	 name2.innerHTML = localStorage.getItem("name2");
	 phone2.innerHTML = localStorage.getItem("phone2");
	 name3.innerHTML = localStorage.getItem("name3");
	 phone3.innerHTML = localStorage.getItem("phone3");
	 name4.innerHTML = localStorage.getItem("name4");
	 phone4.innerHTML = localStorage.getItem("phone4");
	 name5.innerHTML = localStorage.getItem("name5");
	 phone5.innerHTML = localStorage.getItem("phone5");
	 name6.innerHTML = localStorage.getItem("name6");
	 phone6.innerHTML = localStorage.getItem("phone6");
	 name7.innerHTML = localStorage.getItem("name7");
	 phone7.innerHTML = localStorage.getItem("phone7");
	 name8.innerHTML = localStorage.getItem("name8");
	 phone8.innerHTML = localStorage.getItem("phone8");
	 name9.innerHTML = localStorage.getItem("name9");
	 phone9.innerHTML = localStorage.getItem("phone9");
	 name10.innerHTML = localStorage.getItem("name10");
	 phone10.innerHTML = localStorage.getItem("phone10");
	 name11.innerHTML = localStorage.getItem("name11");
	 phone11.innerHTML = localStorage.getItem("phone11");
	 name12.innerHTML = localStorage.getItem("name12");
	 phone12.innerHTML =localStorage.getItem("phone12");
	 name13.innerHTML = localStorage.getItem("name13");
	 phone13.innerHTML = localStorage.getItem("phone13");
	 name14.innerHTML = localStorage.getItem("name14");
	 phone14.innerHTML = localStorage.getItem("phone14");
	 name15.innerHTML = localStorage.getItem("name15");
	 phone15.innerHTML =localStorage.getItem("phone15");
	 name16.innerHTML = localStorage.getItem("name16");
	 phone16.innerHTML = localStorage.getItem("phone16");
	 name17.innerHTML = localStorage.getItem("name17");
	 phone17.innerHTML =localStorage.getItem("phone17");
	 name18.innerHTML = localStorage.getItem("name18");
	 phone18.innerHTML = localStorage.getItem("phone18");
	 name19.innerHTML = localStorage.getItem("name19");
	 phone19.innerHTML = localStorage.getItem("phone19");
	 name20.innerHTML = localStorage.getItem("name20");
	 phone20.innerHTML = localStorage.getItem("phone20");
	 name21.innerHTML = localStorage.getItem("name21");
	 phone21.innerHTML = localStorage.getItem("phone21");
	 name22.innerHTML = localStorage.getItem("name22");
	 phone22.innerHTML = localStorage.getItem("phone22");
	 name23.innerHTML = localStorage.getItem("name23");
	 phone23.innerHTML = localStorage.getItem("phone23");
	 name24.innerHTML = localStorage.getItem("name24");
	 phone24.innerHTML = localStorage.getItem("phone24");
	 name25.innerHTML = localStorage.getItem("name25");
	 phone25.innerHTML = localStorage.getItem("phone25");
	 name26.innerHTML = localStorage.getItem("name26");
	 phone26.innerHTML = localStorage.getItem("phone26");
	 name27.innerHTML = localStorage.getItem("name27");
	 phone27.innerHTML = localStorage.getItem("phone27");
	 name28.innerHTML = localStorage.getItem("name28");
	 phone28.innerHTML = localStorage.getItem("phone28");
	 name29.innerHTML = localStorage.getItem("name29");
	 phone29.innerHTML = localStorage.getItem("phone29");
	 name30.innerHTML = localStorage.getItem("name30");
	 phone30.innerHTML = localStorage.getItem("phone30");
	 name31.innerHTML = localStorage.getItem("name31");
	 phone31.innerHTML = localStorage.getItem("phone31");
	 name32.innerHTML = localStorage.getItem("name32");
	 phone32.innerHTML = localStorage.getItem("phone32");
	 name33.innerHTML = localStorage.getItem("name33");
	 phone33.innerHTML = localStorage.getItem("phone33");
	 name34.innerHTML = localStorage.getItem("name34");
	 phone34.innerHTML = localStorage.getItem("phone34");
	 name35.innerHTML = localStorage.getItem("name35");
	 phone35.innerHTML = localStorage.getItem("phone35");
	 name36.innerHTML = localStorage.getItem("name36");
	 phone36.innerHTML = localStorage.getItem("phone36");
	 name37.innerHTML = localStorage.getItem("name37");
	 phone37.innerHTML = localStorage.getItem("phone37");
	 name38.innerHTML = localStorage.getItem("name38");
	 phone38.innerHTML = localStorage.getItem("phone38");
	 name39.innerHTML = localStorage.getItem("name39");
	 phone39.innerHTML = localStorage.getItem("phone39");
	 name40.innerHTML = localStorage.getItem("name40");
	 phone40.innerHTML = localStorage.getItem("phone40");
	 name41.innerHTML = localStorage.getItem("name41");
	 phone41.innerHTML = localStorage.getItem("phone41");
	 name42.innerHTML = localStorage.getItem("name42");
	 phone42.innerHTML = localStorage.getItem("phone42");
	 name43.innerHTML = localStorage.getItem("name43");
	 phone43.innerHTML = localStorage.getItem("phone43");
	 name44.innerHTML = localStorage.getItem("name44");
	 phone44.innerHTML = localStorage.getItem("phone44");
	 name45.innerHTML = localStorage.getItem("name45");
	 phone45.innerHTML = localStorage.getItem("phone45");
	 name46.innerHTML = localStorage.getItem("name46");
	 phone46.innerHTML = localStorage.getItem("phone46");
	 name47.innerHTML = localStorage.getItem("name47");
	 phone47.innerHTML = localStorage.getItem("phone47");
	 name48.innerHTML = localStorage.getItem("name48");
	 phone48.innerHTML = localStorage.getItem("phone48");
	 name49.innerHTML = localStorage.getItem("name49");
	 phone49.innerHTML = localStorage.getItem("phone49");
	 name50.innerHTML = localStorage.getItem("name50");
	 phone50.innerHTML = localStorage.getItem("phone50");
	 name51.innerHTML = localStorage.getItem("name51");
	 phone51.innerHTML = localStorage.getItem("phone51");
	 name52.innerHTML = localStorage.getItem("name52");
	 phone52.innerHTML = localStorage.getItem("phone52");
	 name53.innerHTML = localStorage.getItem("name53");
	 phone53.innerHTML = localStorage.getItem("phone53");
	 name54.innerHTML = localStorage.getItem("name54");
	 phone54.innerHTML = localStorage.getItem("phone54");
	 name55.innerHTML = localStorage.getItem("name55");
	 phone55.innerHTML = localStorage.getItem("phone55");
	 name56.innerHTML = localStorage.getItem("name56");
	 phone56.innerHTML = localStorage.getItem("phone56");
	 name57.innerHTML = localStorage.getItem("name57");
	 phone57.innerHTML = localStorage.getItem("phone57");
	 name58.innerHTML = localStorage.getItem("name58");
	 phone58.innerHTML = localStorage.getItem("phone58");
	 name59.innerHTML = localStorage.getItem("name59");
	 phone59.innerHTML = localStorage.getItem("phone59");
	 name60.innerHTML = localStorage.getItem("name60");
	 phone60.innerHTML = localStorage.getItem("phone60");
	 name61.innerHTML = localStorage.getItem("name61");
	 phone61.innerHTML = localStorage.getItem("phone61");
	 name62.innerHTML = localStorage.getItem("name62");
	 phone62.innerHTML = localStorage.getItem("phone62");
	 name63.innerHTML = localStorage.getItem("name63");
	 phone63.innerHTML = localStorage.getItem("phone63");
	 name64.innerHTML = localStorage.getItem("name64");
	 phone64.innerHTML = localStorage.getItem("phone64");
	 name65.innerHTML = localStorage.getItem("name65");
	 phone65.innerHTML = localStorage.getItem("phone65");
	 name66.innerHTML = localStorage.getItem("name66");
	 phone66.innerHTML = localStorage.getItem("phone66");
	 name67.innerHTML = localStorage.getItem("name67");
	 phone67.innerHTML = localStorage.getItem("phone67");
	 name68.innerHTML = localStorage.getItem("name68");
	 phone68.innerHTML = localStorage.getItem("phone68");
	 name69.innerHTML = localStorage.getItem("name69");
	 phone69.innerHTML = localStorage.getItem("phone69");
	 name70.innerHTML = localStorage.getItem("name70");
	 phone70.innerHTML = localStorage.getItem("phone70");

	 namebox.value = "";
	 phonebox.value = "";
}//right include text


	
	}//typeofStorageUndefined
}//main click function
const clickShow = () =>{
	opshow.classList.toggle("showcontact");
	opshow.classList.toggle("hidecontact");
	container2.classList.toggle("allheight");
	textboxs.classList.toggle("orgtxtheight");
	textboxs.classList.toggle("textheight");
}
const clickClear = () =>{
	const askpass = prompt("Enter Password to clear all");
	if(askpass === NaN || askpass === null || askpass === "" || askpass !== "2880"){
		sign.style.opacity = "1";
	sign.innerHTML = "❌ Wrong Password";
	setTimeout(()=>{
		sign.style.opacity = "0";
	},800);
	}
	if(askpass === "2880"){
	sign.style.opacity = "1";
	sign.innerHTML = "✅ Contacts all deleted";
	setTimeout(()=>{
		sign.style.opacity = "0";
	},1000);
	localStorage.clickcount = 0;
	localStorage.removeItem("name1");
	 localStorage.removeItem("phone1");
	 localStorage.removeItem("name2");
	 localStorage.removeItem("phone2");
	 localStorage.removeItem("name3");
	 localStorage.removeItem("phone3");
	 localStorage.removeItem("name4");
	 localStorage.removeItem("phone4");
	 localStorage.removeItem("name5");
	 localStorage.removeItem("phone5");
	 localStorage.removeItem("name6");
	 localStorage.removeItem("phone6");
	 localStorage.removeItem("name7");
	 localStorage.removeItem("phone7");
	 localStorage.removeItem("name8");
	 localStorage.removeItem("phone8");
	 localStorage.removeItem("name9");
	 localStorage.removeItem("phone9");
 localStorage.removeItem("name10");
localStorage.removeItem("phone10");
 localStorage.removeItem("name11");
 localStorage.removeItem("phone11");
 localStorage.removeItem("name12");
localStorage.removeItem("phone12");
 localStorage.removeItem("name13");
 localStorage.removeItem("phone13");
 localStorage.removeItem("name14");
 localStorage.removeItem("phone14");
 localStorage.removeItem("name15");
localStorage.removeItem("phone15");
 localStorage.removeItem("name16");
 localStorage.removeItem("phone16");
 localStorage.removeItem("name17");
localStorage.removeItem("phone17");
localStorage.removeItem("name18");
 localStorage.removeItem("phone18");
 localStorage.removeItem("name19");
 localStorage.removeItem("phone19");
	 localStorage.removeItem("name20");
	 localStorage.removeItem("phone20");
	 localStorage.removeItem("name21");
	 localStorage.removeItem("phone21");
	 localStorage.removeItem("name22");
	 localStorage.removeItem("phone22");
	 localStorage.removeItem("name23");
	 localStorage.removeItem("phone23");
	 localStorage.removeItem("name24");
	 localStorage.removeItem("phone24");
	 localStorage.removeItem("name25");
	 localStorage.removeItem("phone25");
	 localStorage.removeItem("name26");
	 localStorage.removeItem("phone26");
	 localStorage.removeItem("name27");
	 localStorage.removeItem("phone27");
	 localStorage.removeItem("name28");
	 localStorage.removeItem("phone28");
	 localStorage.removeItem("name29");
	 localStorage.removeItem("phone29");
	 localStorage.removeItem("name30");
	 localStorage.removeItem("phone30");
	 localStorage.removeItem("name31");
	 localStorage.removeItem("phone31");
	 localStorage.removeItem("name32");
	 localStorage.removeItem("phone32");
	 localStorage.removeItem("name33");
	 localStorage.removeItem("phone33");
	 localStorage.removeItem("name34");
	 localStorage.removeItem("phone34");
	 localStorage.removeItem("name35");
	 localStorage.removeItem("phone35");
	 localStorage.removeItem("name36");
	 localStorage.removeItem("phone36");
	 localStorage.removeItem("name37");
	 localStorage.removeItem("phone37");
	 localStorage.removeItem("name38");
	 localStorage.removeItem("phone38");
	 localStorage.removeItem("name39");
	 localStorage.removeItem("phone39");
	 localStorage.removeItem("name40");
	 localStorage.removeItem("phone40");
	 localStorage.removeItem("name41");
	 localStorage.removeItem("phone41");
	 localStorage.removeItem("name42");
	 localStorage.removeItem("phone42");
	 localStorage.removeItem("name43");
	 localStorage.removeItem("phone43");
	 localStorage.removeItem("name44");
	 localStorage.removeItem("phone44");
	 localStorage.removeItem("name45");
	 localStorage.removeItem("phone45");
	 localStorage.removeItem("name46");
	 localStorage.removeItem("phone46");
	 localStorage.removeItem("name47");
	 localStorage.removeItem("phone47");
	 localStorage.removeItem("name48");
	 localStorage.removeItem("phone48");
	 localStorage.removeItem("name49");
	 localStorage.removeItem("phone49");
	 localStorage.removeItem("name50");
	 localStorage.removeItem("phone50");
	 localStorage.removeItem("name51");
	 localStorage.removeItem("phone51");
	 localStorage.removeItem("name52");
	 localStorage.removeItem("phone52");
	 localStorage.removeItem("name53");
	 localStorage.removeItem("phone53");
	 localStorage.removeItem("name54");
	 localStorage.removeItem("phone54");
	 localStorage.removeItem("name55");
	 localStorage.removeItem("phone55");
	 localStorage.removeItem("name56");
	 localStorage.removeItem("phone56");
	 localStorage.removeItem("name57");
	 localStorage.removeItem("phone57");
	 localStorage.removeItem("name58");
	 localStorage.removeItem("phone58");
	 localStorage.removeItem("name59");
	 localStorage.removeItem("phone59");
	 localStorage.removeItem("name60");
	 localStorage.removeItem("phone60");
	 localStorage.removeItem("name61");
	 localStorage.removeItem("phone61");
	 localStorage.removeItem("name62");
	 localStorage.removeItem("phone62");
	 localStorage.removeItem("name63");
	 localStorage.removeItem("phone63");
	 localStorage.removeItem("name64");
	 localStorage.removeItem("phone64");
	 localStorage.removeItem("name65");
	 localStorage.removeItem("phone65");
	 localStorage.removeItem("name66");
	 localStorage.removeItem("phone66");
	 localStorage.removeItem("name67");
	 localStorage.removeItem("phone67");
	 localStorage.removeItem("name68");
	 localStorage.removeItem("phone68");
	 localStorage.removeItem("name69");
	 localStorage.removeItem("phone69");
	 localStorage.removeItem("name70");
	 localStorage.removeItem("phone70");
	 name1.innerHTML = localStorage.getItem("name1");
	 phone1.innerHTML = localStorage.getItem("phone1");
	 name2.innerHTML = localStorage.getItem("name2");
	 phone2.innerHTML = localStorage.getItem("phone2");
	 name3.innerHTML = localStorage.getItem("name3");
	 phone3.innerHTML = localStorage.getItem("phone3");
	 name4.innerHTML = localStorage.getItem("name4");
	 phone4.innerHTML = localStorage.getItem("phone4");
	 name5.innerHTML = localStorage.getItem("name5");
	 phone5.innerHTML = localStorage.getItem("phone5");
	 name6.innerHTML = localStorage.getItem("name6");
	 phone6.innerHTML = localStorage.getItem("phone6");
	 name7.innerHTML = localStorage.getItem("name7");
	 phone7.innerHTML = localStorage.getItem("phone7");
	 name8.innerHTML = localStorage.getItem("name8");
	 phone8.innerHTML = localStorage.getItem("phone8");
	 name9.innerHTML = localStorage.getItem("name9");
	 phone9.innerHTML = localStorage.getItem("phone9");
	 name10.innerHTML = localStorage.getItem("name10");
	 phone10.innerHTML = localStorage.getItem("phone10");
	 name11.innerHTML = localStorage.getItem("name11");
	 phone11.innerHTML = localStorage.getItem("phone11");
	 name12.innerHTML = localStorage.getItem("name12");
	 phone12.innerHTML =localStorage.getItem("phone12");
	 name13.innerHTML = localStorage.getItem("name13");
	 phone13.innerHTML = localStorage.getItem("phone13");
	 name14.innerHTML = localStorage.getItem("name14");
	 phone14.innerHTML = localStorage.getItem("phone14");
	 name15.innerHTML = localStorage.getItem("name15");
	 phone15.innerHTML =localStorage.getItem("phone15");
	 name16.innerHTML = localStorage.getItem("name16");
	 phone16.innerHTML = localStorage.getItem("phone16");
	 name17.innerHTML = localStorage.getItem("name17");
	 phone17.innerHTML =localStorage.getItem("phone17");
	 name18.innerHTML = localStorage.getItem("name18");
	 phone18.innerHTML = localStorage.getItem("phone18");
	 name19.innerHTML = localStorage.getItem("name19");
	 phone19.innerHTML = localStorage.getItem("phone19");
	 name20.innerHTML = localStorage.getItem("name20");
	 phone20.innerHTML = localStorage.getItem("phone20");
	 name21.innerHTML = localStorage.getItem("name21");
	 phone21.innerHTML = localStorage.getItem("phone21");
	 name22.innerHTML = localStorage.getItem("name22");
	 phone22.innerHTML = localStorage.getItem("phone22");
	 name23.innerHTML = localStorage.getItem("name23");
	 phone23.innerHTML = localStorage.getItem("phone23");
	 name24.innerHTML = localStorage.getItem("name24");
	 phone24.innerHTML = localStorage.getItem("phone24");
	 name25.innerHTML = localStorage.getItem("name25");
	 phone25.innerHTML = localStorage.getItem("phone25");
	 name26.innerHTML = localStorage.getItem("name26");
	 phone26.innerHTML = localStorage.getItem("phone26");
	 name27.innerHTML = localStorage.getItem("name27");
	 phone27.innerHTML = localStorage.getItem("phone27");
	 name28.innerHTML = localStorage.getItem("name28");
	 phone28.innerHTML = localStorage.getItem("phone28");
	 name29.innerHTML = localStorage.getItem("name29");
	 phone29.innerHTML = localStorage.getItem("phone29");
	 name30.innerHTML = localStorage.getItem("name30");
	 phone30.innerHTML = localStorage.getItem("phone30");
	 name31.innerHTML = localStorage.getItem("name31");
	 phone31.innerHTML = localStorage.getItem("phone31");
	 name32.innerHTML = localStorage.getItem("name32");
	 phone32.innerHTML = localStorage.getItem("phone32");
	 name33.innerHTML = localStorage.getItem("name33");
	 phone33.innerHTML = localStorage.getItem("phone33");
	 name34.innerHTML = localStorage.getItem("name34");
	 phone34.innerHTML = localStorage.getItem("phone34");
	 name35.innerHTML = localStorage.getItem("name35");
	 phone35.innerHTML = localStorage.getItem("phone35");
	 name36.innerHTML = localStorage.getItem("name36");
	 phone36.innerHTML = localStorage.getItem("phone36");
	 name37.innerHTML = localStorage.getItem("name37");
	 phone37.innerHTML = localStorage.getItem("phone37");
	 name38.innerHTML = localStorage.getItem("name38");
	 phone38.innerHTML = localStorage.getItem("phone38");
	 name39.innerHTML = localStorage.getItem("name39");
	 phone39.innerHTML = localStorage.getItem("phone39");
	 name40.innerHTML = localStorage.getItem("name40");
	 phone40.innerHTML = localStorage.getItem("phone40");
	 name41.innerHTML = localStorage.getItem("name41");
	 phone41.innerHTML = localStorage.getItem("phone41");
	 name42.innerHTML = localStorage.getItem("name42");
	 phone42.innerHTML = localStorage.getItem("phone42");
	 name43.innerHTML = localStorage.getItem("name43");
	 phone43.innerHTML = localStorage.getItem("phone43");
	 name44.innerHTML = localStorage.getItem("name44");
	 phone44.innerHTML = localStorage.getItem("phone44");
	 name45.innerHTML = localStorage.getItem("name45");
	 phone45.innerHTML = localStorage.getItem("phone45");
	 name46.innerHTML = localStorage.getItem("name46");
	 phone46.innerHTML = localStorage.getItem("phone46");
	 name47.innerHTML = localStorage.getItem("name47");
	 phone47.innerHTML = localStorage.getItem("phone47");
	 name48.innerHTML = localStorage.getItem("name48");
	 phone48.innerHTML = localStorage.getItem("phone48");
	 name49.innerHTML = localStorage.getItem("name49");
	 phone49.innerHTML = localStorage.getItem("phone49");
	 name50.innerHTML = localStorage.getItem("name50");
	 phone50.innerHTML = localStorage.getItem("phone50");
	 name51.innerHTML = localStorage.getItem("name51");
	 phone51.innerHTML = localStorage.getItem("phone51");
	 name52.innerHTML = localStorage.getItem("name52");
	 phone52.innerHTML = localStorage.getItem("phone52");
	 name53.innerHTML = localStorage.getItem("name53");
	 phone53.innerHTML = localStorage.getItem("phone53");
	 name54.innerHTML = localStorage.getItem("name54");
	 phone54.innerHTML = localStorage.getItem("phone54");
	 name55.innerHTML = localStorage.getItem("name55");
	 phone55.innerHTML = localStorage.getItem("phone55");
	 name56.innerHTML = localStorage.getItem("name56");
	 phone56.innerHTML = localStorage.getItem("phone56");
	 name57.innerHTML = localStorage.getItem("name57");
	 phone57.innerHTML = localStorage.getItem("phone57");
	 name58.innerHTML = localStorage.getItem("name58");
	 phone58.innerHTML = localStorage.getItem("phone58");
	 name59.innerHTML = localStorage.getItem("name59");
	 phone59.innerHTML = localStorage.getItem("phone59");
	 name60.innerHTML = localStorage.getItem("name60");
	 phone60.innerHTML = localStorage.getItem("phone60");
	 name61.innerHTML = localStorage.getItem("name61");
	 phone61.innerHTML = localStorage.getItem("phone61");
	 name62.innerHTML = localStorage.getItem("name62");
	 phone62.innerHTML = localStorage.getItem("phone62");
	 name63.innerHTML = localStorage.getItem("name63");
	 phone63.innerHTML = localStorage.getItem("phone63");
	 name64.innerHTML = localStorage.getItem("name64");
	 phone64.innerHTML = localStorage.getItem("phone64");
	 name65.innerHTML = localStorage.getItem("name65");
	 phone65.innerHTML = localStorage.getItem("phone65");
	 name66.innerHTML = localStorage.getItem("name66");
	 phone66.innerHTML = localStorage.getItem("phone66");
	 name67.innerHTML = localStorage.getItem("name67");
	 phone67.innerHTML = localStorage.getItem("phone67");
	 name68.innerHTML = localStorage.getItem("name68");
	 phone68.innerHTML = localStorage.getItem("phone68");
	 name69.innerHTML = localStorage.getItem("name69");
	 phone69.innerHTML = localStorage.getItem("phone69");
	 name70.innerHTML = localStorage.getItem("name70");
	 phone70.innerHTML = localStorage.getItem("phone70");
}//close clear function
}// close right passcode

	name1.innerHTML = localStorage.getItem("name1");
	 phone1.innerHTML = localStorage.getItem("phone1");
	 name2.innerHTML = localStorage.getItem("name2");
	 phone2.innerHTML = localStorage.getItem("phone2");
	 name3.innerHTML = localStorage.getItem("name3");
	 phone3.innerHTML = localStorage.getItem("phone3");
	 name4.innerHTML = localStorage.getItem("name4");
	 phone4.innerHTML = localStorage.getItem("phone4");
	 name5.innerHTML = localStorage.getItem("name5");
	 phone5.innerHTML = localStorage.getItem("phone5");
	 name6.innerHTML = localStorage.getItem("name6");
	 phone6.innerHTML = localStorage.getItem("phone6");
	 name7.innerHTML = localStorage.getItem("name7");
	 phone7.innerHTML = localStorage.getItem("phone7");
	 name8.innerHTML = localStorage.getItem("name8");
	 phone8.innerHTML = localStorage.getItem("phone8");
	 name9.innerHTML = localStorage.getItem("name9");
	 phone9.innerHTML = localStorage.getItem("phone9");
	 name10.innerHTML = localStorage.getItem("name10");
	 phone10.innerHTML = localStorage.getItem("phone10");
	 name11.innerHTML = localStorage.getItem("name11");
	 phone11.innerHTML = localStorage.getItem("phone11");
	 name12.innerHTML = localStorage.getItem("name12");
	 phone12.innerHTML =localStorage.getItem("phone12");
	 name13.innerHTML = localStorage.getItem("name13");
	 phone13.innerHTML = localStorage.getItem("phone13");
	 name14.innerHTML = localStorage.getItem("name14");
	 phone14.innerHTML = localStorage.getItem("phone14");
	 name15.innerHTML = localStorage.getItem("name15");
	 phone15.innerHTML =localStorage.getItem("phone15");
	 name16.innerHTML = localStorage.getItem("name16");
	 phone16.innerHTML = localStorage.getItem("phone16");
	 name17.innerHTML = localStorage.getItem("name17");
	 phone17.innerHTML =localStorage.getItem("phone17");
	 name18.innerHTML = localStorage.getItem("name18");
	 phone18.innerHTML = localStorage.getItem("phone18");
	 name19.innerHTML = localStorage.getItem("name19");
	 phone19.innerHTML = localStorage.getItem("phone19");
	 name20.innerHTML = localStorage.getItem("name20");
	 phone20.innerHTML = localStorage.getItem("phone20");
	 name21.innerHTML = localStorage.getItem("name21");
	 phone21.innerHTML = localStorage.getItem("phone21");
	 name22.innerHTML = localStorage.getItem("name22");
	 phone22.innerHTML = localStorage.getItem("phone22");
	 name23.innerHTML = localStorage.getItem("name23");
	 phone23.innerHTML = localStorage.getItem("phone23");
	 name24.innerHTML = localStorage.getItem("name24");
	 phone24.innerHTML = localStorage.getItem("phone24");
	 name25.innerHTML = localStorage.getItem("name25");
	 phone25.innerHTML = localStorage.getItem("phone25");
	 name26.innerHTML = localStorage.getItem("name26");
	 phone26.innerHTML = localStorage.getItem("phone26");
	 name27.innerHTML = localStorage.getItem("name27");
	 phone27.innerHTML = localStorage.getItem("phone27");
	 name28.innerHTML = localStorage.getItem("name28");
	 phone28.innerHTML = localStorage.getItem("phone28");
	 name29.innerHTML = localStorage.getItem("name29");
	 phone29.innerHTML = localStorage.getItem("phone29");
	 name30.innerHTML = localStorage.getItem("name30");
	 phone30.innerHTML = localStorage.getItem("phone30");
	 name31.innerHTML = localStorage.getItem("name31");
	 phone31.innerHTML = localStorage.getItem("phone31");
	 name32.innerHTML = localStorage.getItem("name32");
	 phone32.innerHTML = localStorage.getItem("phone32");
	 name33.innerHTML = localStorage.getItem("name33");
	 phone33.innerHTML = localStorage.getItem("phone33");
	 name34.innerHTML = localStorage.getItem("name34");
	 phone34.innerHTML = localStorage.getItem("phone34");
	 name35.innerHTML = localStorage.getItem("name35");
	 phone35.innerHTML = localStorage.getItem("phone35");
	 name36.innerHTML = localStorage.getItem("name36");
	 phone36.innerHTML = localStorage.getItem("phone36");
	 name37.innerHTML = localStorage.getItem("name37");
	 phone37.innerHTML = localStorage.getItem("phone37");
	 name38.innerHTML = localStorage.getItem("name38");
	 phone38.innerHTML = localStorage.getItem("phone38");
	 name39.innerHTML = localStorage.getItem("name39");
	 phone39.innerHTML = localStorage.getItem("phone39");
	 name40.innerHTML = localStorage.getItem("name40");
	 phone40.innerHTML = localStorage.getItem("phone40");
	 name41.innerHTML = localStorage.getItem("name41");
	 phone41.innerHTML = localStorage.getItem("phone41");
	 name42.innerHTML = localStorage.getItem("name42");
	 phone42.innerHTML = localStorage.getItem("phone42");
	 name43.innerHTML = localStorage.getItem("name43");
	 phone43.innerHTML = localStorage.getItem("phone43");
	 name44.innerHTML = localStorage.getItem("name44");
	 phone44.innerHTML = localStorage.getItem("phone44");
	 name45.innerHTML = localStorage.getItem("name45");
	 phone45.innerHTML = localStorage.getItem("phone45");
	 name46.innerHTML = localStorage.getItem("name46");
	 phone46.innerHTML = localStorage.getItem("phone46");
	 name47.innerHTML = localStorage.getItem("name47");
	 phone47.innerHTML = localStorage.getItem("phone47");
	 name48.innerHTML = localStorage.getItem("name48");
	 phone48.innerHTML = localStorage.getItem("phone48");
	 name49.innerHTML = localStorage.getItem("name49");
	 phone49.innerHTML = localStorage.getItem("phone49");
	 name50.innerHTML = localStorage.getItem("name50");
	 phone50.innerHTML = localStorage.getItem("phone50");
	 name51.innerHTML = localStorage.getItem("name51");
	 phone51.innerHTML = localStorage.getItem("phone51");
	 name52.innerHTML = localStorage.getItem("name52");
	 phone52.innerHTML = localStorage.getItem("phone52");
	 name53.innerHTML = localStorage.getItem("name53");
	 phone53.innerHTML = localStorage.getItem("phone53");
	 name54.innerHTML = localStorage.getItem("name54");
	 phone54.innerHTML = localStorage.getItem("phone54");
	 name55.innerHTML = localStorage.getItem("name55");
	 phone55.innerHTML = localStorage.getItem("phone55");
	 name56.innerHTML = localStorage.getItem("name56");
	 phone56.innerHTML = localStorage.getItem("phone56");
	 name57.innerHTML = localStorage.getItem("name57");
	 phone57.innerHTML = localStorage.getItem("phone57");
	 name58.innerHTML = localStorage.getItem("name58");
	 phone58.innerHTML = localStorage.getItem("phone58");
	 name59.innerHTML = localStorage.getItem("name59");
	 phone59.innerHTML = localStorage.getItem("phone59");
	 name60.innerHTML = localStorage.getItem("name60");
	 phone60.innerHTML = localStorage.getItem("phone60");
	 name61.innerHTML = localStorage.getItem("name61");
	 phone61.innerHTML = localStorage.getItem("phone61");
	 name62.innerHTML = localStorage.getItem("name62");
	 phone62.innerHTML = localStorage.getItem("phone62");
	 name63.innerHTML = localStorage.getItem("name63");
	 phone63.innerHTML = localStorage.getItem("phone63");
	 name64.innerHTML = localStorage.getItem("name64");
	 phone64.innerHTML = localStorage.getItem("phone64");
	 name65.innerHTML = localStorage.getItem("name65");
	 phone65.innerHTML = localStorage.getItem("phone65");
	 name66.innerHTML = localStorage.getItem("name66");
	 phone66.innerHTML = localStorage.getItem("phone66");
	 name67.innerHTML = localStorage.getItem("name67");
	 phone67.innerHTML = localStorage.getItem("phone67");
	 name68.innerHTML = localStorage.getItem("name68");
	 phone68.innerHTML = localStorage.getItem("phone68");
	 name69.innerHTML = localStorage.getItem("name69");
	 phone69.innerHTML = localStorage.getItem("phone69");
	 name70.innerHTML = localStorage.getItem("name70");
	 phone70.innerHTML = localStorage.getItem("phone70");